In [24]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [25]:
data = {
    "Fever" : [98,99,100,101,102,103,98,99,101,102],
    "Cough" : [0,0,1,1,1,1,0,1,1,1],
    "BreathingProblem" : [0,0,0,1,1,1,0,0,1,1],
    "COVID_Status" : [
        "Negative","Negative","Negative",
        "Positive","Positive","Positive",
        "Negative","Negative","Positive","Positive"
    ]
}

df=pd.DataFrame(data)

In [26]:
df

   Fever  Cough  BreathingProblem COVID_Status
0     98      0                 0     Negative
1     99      0                 0     Negative
2    100      1                 0     Negative
3    101      1                 1     Positive
4    102      1                 1     Positive
5    103      1                 1     Positive
6     98      0                 0     Negative
7     99      1                 0     Negative
8    101      1                 1     Positive
9    102      1                 1     Positive

In [27]:
df["COVID_Status"]=df["COVID_Status"].map({"Negative":0, "Positive":1})
df.astype(int)

   Fever  Cough  BreathingProblem  COVID_Status
0     98      0                 0             0
1     99      0                 0             0
2    100      1                 0             0
3    101      1                 1             1
4    102      1                 1             1
5    103      1                 1             1
6     98      0                 0             0
7     99      1                 0             0
8    101      1                 1             1
9    102      1                 1             1

In [29]:
X = df[["Fever","Cough","BreathingProblem"]]
y = df["COVID_Status"]

model = DecisionTreeClassifier()
model.fit(X,y)

Fever = float(input("Enter your temprature: "))
cough = float(input("Enter your cough status (1 for yes) (0 for no) : "))
breathprob = float(input("do you have breathing rpoblem (1 for yes) (0 for no): "))

prediction = model.predict([[Fever,cough,breathprob]])[0]
probability = model.predict_proba([[Fever,cough,breathprob]])


print("\nProbability: ","postive" if prediction == 1 else "negative")
print("negative Probability = ", round(probability[0][0] * 100,2), "%")
print("Positive Probability = ", round(probability[0][1] * 100,2), "%")

y_pred = model.predict(X)
accuracy = accuracy_score(y, y_pred)
print("Accuracy: ", accuracy * 100, "%")

Enter your temprature:  101
Enter your cough status (1 for yes) (0 for no) :  0
do you have breathing rpoblem (1 for yes) (0 for no):  0

Probability:  negative
negative Probability =  100.0 %
Positive Probability =  0.0 %
Accuracy:  100.0 %

D:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
D:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(