In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [15]:
df = pd.read_csv("../DataSet/loan_approval_dataset.csv")
df

      loan_id   no_of_dependents  ...  bank_asset_value  loan_status
0           1                  2  ...           8000000     Approved
1           2                  0  ...           3300000     Rejected
2           3                  3  ...          12800000     Rejected
3           4                  3  ...           7900000     Rejected
4           5                  5  ...           5000000     Rejected
...       ...                ...  ...               ...          ...
4264     4265                  5  ...            800000     Rejected
4265     4266                  0  ...           1900000     Approved
4266     4267                  2  ...           7300000     Rejected
4267     4268                  1  ...           5800000     Approved
4268     4269                  1  ...          12000000     Approved

[4269 rows x 13 columns]

In [16]:
df.isna().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.describe()

           loan_id   no_of_dependents  ...   luxury_assets_value   bank_asset_value
count  4269.000000        4269.000000  ...          4.269000e+03       4.269000e+03
mean   2135.000000           2.498712  ...          1.512631e+07       4.976692e+06
std    1232.498479           1.695910  ...          9.103754e+06       3.250185e+06
min       1.000000           0.000000  ...          3.000000e+05       0.000000e+00
25%    1068.000000           1.000000  ...          7.500000e+06       2.300000e+06
50%    2135.000000           3.000000  ...          1.460000e+07       4.600000e+06
75%    3202.000000           4.000000  ...          2.170000e+07       7.100000e+06
max    4269.000000           5.000000  ...          3.920000e+07       1.470000e+07

[8 rows x 10 columns]

In [19]:
df.index

RangeIndex(start=0, stop=4269, step=1)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

In [21]:
# First, strip whitespace from column names just in case
df.columns = df.columns.str.strip()

# Convert to boolean (True if Graduate, False otherwise)
df['education'] = df['education'].str.strip() == 'Graduate'

In [22]:
# Convert Boolean (True/False) to Integer (1/0)
df['education'] = df['education'].astype(int)

In [23]:
# 1. Strip the hidden leading spaces from the text values
df['self_employed'] = df['self_employed'].str.strip()

# 2. Map 'Yes' to 1 and 'No' to 0
df['self_employed'] = df['self_employed'].map({'Yes': 1, 'No': 0})

In [24]:
# 1. Clean the column names to remove hidden spaces
df.columns = df.columns.str.strip()

# 2. Combine all asset columns into a new column called 'total_assets'
df['total_assets'] = (
    df['residential_assets_value'] + 
    df['commercial_assets_value'] + 
    df['luxury_assets_value'] + 
    df['bank_asset_value']
)

In [25]:
df

      loan_id  no_of_dependents  ...  loan_status  total_assets
0           1                 2  ...     Approved      50700000
1           2                 0  ...     Rejected      17000000
2           3                 3  ...     Rejected      57700000
3           4                 3  ...     Rejected      52700000
4           5                 5  ...     Rejected      55000000
...       ...               ...  ...          ...           ...
4264     4265                 5  ...     Rejected       7400000
4265     4266                 0  ...     Approved      20000000
4266     4267                 2  ...     Rejected      39000000
4267     4268                 1  ...     Approved      28800000
4268     4269                 1  ...     Approved      77300000

[4269 rows x 14 columns]

In [26]:
df.head()

   loan_id  no_of_dependents  ...  loan_status  total_assets
0        1                 2  ...     Approved      50700000
1        2                 0  ...     Rejected      17000000
2        3                 3  ...     Rejected      57700000
3        4                 3  ...     Rejected      52700000
4        5                 5  ...     Rejected      55000000

[5 rows x 14 columns]

In [31]:
col = ["education","self_employed","income_annum","loan_amount","loan_term","cibil_score","total_assets","loan_status"]
df_clean = df[col].copy()
df_clean

      education  self_employed  ...  total_assets  loan_status
0             1              0  ...      50700000     Approved
1             0              1  ...      17000000     Rejected
2             1              0  ...      57700000     Rejected
3             1              0  ...      52700000     Rejected
4             0              1  ...      55000000     Rejected
...         ...            ...  ...           ...          ...
4264          1              1  ...       7400000     Rejected
4265          0              1  ...      20000000     Approved
4266          0              0  ...      39000000     Rejected
4267          0              0  ...      28800000     Approved
4268          1              0  ...      77300000     Approved

[4269 rows x 8 columns]

In [34]:
X = df[["education","self_employed","income_annum","loan_amount","loan_term","cibil_score","total_assets"]]
y = df["loan_status"]

model = LogisticRegression()
model.fit(X,y)

education = int(input("Enter education (1 for Graduate, 0 for Not Graduate): "))
self_employed = int(input("Are you self-employed? (1 for Yes, 0 for No): "))
income_annum = float(input("Enter annual income (e.g., 5000000): "))
loan_amount = float(input("Enter loan amount requested: "))
loan_term = int(input("Enter loan term in months: "))
cibil_score = int(input("Enter CIBIL/Credit score (300-900): "))
total_assets = float(input("Enter total value of all assets combined: "))



prediction = model.predict([[education,self_employed,income_annum,loan_amount,loan_term,cibil_score,total_assets]])
print("\n Prediction: ", prediction[0])
probability = model.predict_proba([[education,self_employed,income_annum,loan_amount,loan_term,cibil_score,total_assets]])

print("Rejected Probability = ", round(probability[0][0] * 100,2), "%")
print("Accepted Probability = ", round(probability[0][1] * 100,2), "%")

y_pred = model.predict(X)
accuracy = accuracy_score(y, y_pred)
print("Accuracy: ", accuracy * 100, "%")

D:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Enter education (1 for Graduate, 0 for Not Graduate):  1
Are you self-employed? (1 for Yes, 0 for No):  1
Enter annual income (e.g., 5000000):  1200000
Enter loan amount requested:  3000000
Enter loan term in months:  36
Enter CIBIL/Credit score (300-900):  900
Enter total value of all assets combined:  50000000

 Prediction:   Rejected
Rejected Probability =  30.41 %
Accepted Probability =  69.59 %
Accuracy:  77.91051768564067 %

D:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
D:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(