In [2]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("../DataSet/WorldCups.csv")
df

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810

In [4]:
df.sample(10)

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197

In [5]:
df.isna().sum()

Year              0
Country           0
Winner            0
Runners-Up        0
Third             0
Fourth            0
GoalsScored       0
QualifiedTeams    0
MatchesPlayed     0
Attendance        0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
col = ["Year", "GoalsScored", "QualifiedTeams", "MatchesPlayed"]
X = df[col]
y = df["Winner"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

print("\nEnter World Cup Tournament Stats")
print("Valid Ranges: ")
print("Year : 1930 - 2014")
print("Goals Scored : 70 - 171")
print("Qualified Teams : 13 - 32")
print("Matches Played : 17 - 64")

year = float(input("\nYear (1930 - 2014): "))
goals_scored = float(input("Goals Scored (70 - 171): "))
qualified_teams = float(input("Qualified Teams (13 - 32): "))
matches_played = float(input("Matches Played (17 - 64): "))

prediction = model.predict([[year, goals_scored, qualified_teams, matches_played]])
print("\nPredicted Winner: ", prediction[0])

y_pred = model.predict(X_test)
print("Accuracy :", accuracy_score(y_test, y_pred) * 100)

Enter World Cup Tournament Stats
Valid Ranges:
Year : 1930 - 2014
Goals Scored : 70 - 171
Qualified Teams : 13 - 32
Matches Played : 17 - 64

Year (1930 - 2014):  2012
Goals Scored (70 - 171):  15
Qualified Teams (13 - 32):  15
Matches Played (17 - 64):  50

Predicted Winner:  Spain
Accuracy : 25.0

D:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(